import { Article, Category } from '../types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'World', slug: 'world' },
  { id: '2', name: 'Politics', slug: 'politics' },
  { id: '3', name: 'Tech', slug: 'tech' },
  { id: '4', name: 'Business', slug: 'business' },
  { id: '5', name: 'Sports', slug: 'sports' },
  { id: '6', name: 'Entertainment', slug: 'entertainment' },
];

export const MOCK_ARTICLES: Article[] = [
  {
    id: '101',
    title: "Global Summit Reaches Historic Agreement on Climate Action",
    slug: "global-summit-climate-action",
    excerpt: "Leaders from 190 nations have signed a binding resolution to reduce carbon emissions by 40% before 2030, marking a turning point in environmental policy.",
    content: "<p>In a landmark decision in Geneva today, world leaders united to sign the '2030 Accord'. This agreement represents the most aggressive stance on climate change since the Paris Agreement. Critics argue implementation will be costly, but proponents say the cost of inaction is far higher.</p><p>Key takeaways include:</p><ul><li>Mandatory carbon taxes for heavy industry.</li><li>Subsidies for renewable energy infrastructure.</li><li>Protection for 30% of the world's oceans.</li></ul><p>The summit concluded with a speech from the UN Secretary General, emphasizing that 'the time for debate has passed; the era of action has begun.'</p>",
    coverImage: "https://picsum.photos/seed/news1/800/600",
    authorId: "u1",
    authorName: "Elena Fisher",
    categoryId: "1",
    categoryName: "World",
    tags: ["Climate", "Politics", "Summit"],
    status: "published",
    publishedAt: new Date().toISOString(),
    views: 12500
  },
  {
    id: '102',
    title: "Quantum Computing: The Leap from Lab to Living Room",
    slug: "quantum-computing-leap",
    excerpt: "New breakthroughs in stable qubits suggest that consumer-grade quantum processors might be closer than we think.",
    content: "<p>Tech giant CyberDyne revealed their new 'Q-Core' processor yesterday. Unlike previous models requiring absolute zero temperatures, the Q-Core operates at room temperature using diamond-vacancy technology.</p><p>This development could revolutionize fields from cryptography to pharmaceutical research. However, security experts warn that current encryption standards could be rendered obsolete within five years.</p>",
    coverImage: "https://picsum.photos/seed/tech1/800/600",
    authorId: "u2",
    authorName: "Marcus Chen",
    categoryId: "3",
    categoryName: "Tech",
    tags: ["Quantum", "Hardware", "Future"],
    status: "published",
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    views: 8900
  },
  {
    id: '103',
    title: "Market Rally: Tech Stocks Surge Amidst Inflation Fears",
    slug: "market-rally-tech-surge",
    excerpt: "Despite looming interest rate hikes, the NASDAQ posted its best week in two years, driven by AI sector growth.",
    content: "<p>Wall Street defied expectations this week. Analysts point to the 'AI Gold Rush' as the primary driver, with companies integrating generative AI seeing stock prices jump by an average of 15%.</p>",
    coverImage: "https://picsum.photos/seed/finance1/800/600",
    authorId: "u3",
    authorName: "Sarah Jenkins",
    categoryId: "4",
    categoryName: "Business",
    tags: ["Stocks", "Economy", "AI"],
    status: "published",
    publishedAt: new Date(Date.now() - 172800000).toISOString(),
    views: 5400
  },
  {
    id: '104',
    title: "Championship Final: Underdogs Take the Trophy",
    slug: "championship-underdogs",
    excerpt: "In a stunning upset, the City Hawks defeated the reigning champions 3-2 in overtime.",
    content: "<p>It was a match for the history books. Down 2-0 at halftime, the Hawks rallied with a tactical shift that left the Titans scrambling.</p>",
    coverImage: "https://picsum.photos/seed/sports1/800/600",
    authorId: "u4",
    authorName: "Tom Brady (Not that one)",
    categoryId: "5",
    categoryName: "Sports",
    tags: ["Football", "Finals"],
    status: "published",
    publishedAt: new Date(Date.now() - 200000).toISOString(),
    views: 22000
  },
  {
    id: '105',
    title: "The Return of Minimalist Architecture",
    slug: "minimalist-architecture-return",
    excerpt: "Why concrete and glass are making a comeback in modern residential design.",
    content: "<p>Architects are stripping away the ornamentation of the 2010s. The new wave of 'Brutalist Chic' emphasizes raw materials and light.</p>",
    coverImage: "https://picsum.photos/seed/life1/800/600",
    authorId: "u1",
    authorName: "Elena Fisher",
    categoryId: "6",
    categoryName: "Entertainment",
    tags: ["Design", "Living"],
    status: "published",
    publishedAt: new Date(Date.now() - 400000000).toISOString(),
    views: 1200
  },
  {
      id: '106',
      title: "Local Elections: What You Need to Know",
      slug: "local-elections-guide",
      excerpt: "A comprehensive guide to the candidates and propositions on the ballot this Tuesday.",
      content: "<p>Voters head to the polls this week to decide on key infrastructure bonds and mayoral seats. Here is a breakdown of Proposition A...</p>",
      coverImage: "https://picsum.photos/seed/politics/800/600",
      authorId: "u5",
      authorName: "James O'Connell",
      categoryId: "2",
      categoryName: "Politics",
      tags: ["Election", "Local"],
      status: "published",
      publishedAt: new Date().toISOString(),
      views: 3100
  }
];